package com.enfotrix.cgs_principal_portal.Models

data class StudentModel(

    var Address: String = "",
    var AdmissionDate: String = "",
    var AdmissionFeeStatus:String="",
    var BForm: String = "",
    var BloodGroup: String = "",
    var Cast: String = "",
    var CurrentClass: String = "",
    var CurrentSection: String = "",
    var CurrentSectionName: String = "",
    var DOB: String = "",
    var Department:String="",
    var DischargeDate:String="",
    var DischargeReason:String="",
    var DiscountFacility: Boolean = false,
    var DiscountID:String="",
    var DiscountPercent:String="",
    var DiscountType:String="",
    var Dues: String = "",
    var Email: String = "",
    var ExtraFeeAdjustment:String="",
    var FatherCNIC: String = "",
    var FatherEmail: String = "",
    var FatherIncome: String = "",
    var FatherName:String="",
    var FatherPhoneNumber: String = "",
    var FatherPhoneNumber2: String = "",
    var FatherProfession: String = "",
    var FatherWhatsappNumber: String = "",
    var FeeAdjustmentDiscount:String="",
    var FeeNum:String="",
    var FirstName: String = "",
    var Gender: String = "",
    var HostelFacility: Boolean = false,
    var LastName: String = "",
    var MedicalHistory: String = "",
    var Medium:String="",
    var Migrated: Boolean = false,
    var Password: String = "",
    var PreviousSchool: String = "",
    var PromoteDate:String="",
    var RegNumber: String = "",
    var Religion: String = "",
    var RestoreDate:String="",
    var ShiftedCGS: Boolean = false,
    var Status:String="",
    var StudentId: String = "",
    var StudentName:String="",
    var TransportFacility: Boolean = false,
    var TransportRouteID: String = ""
)